In [1]:
import numpy as np


In [4]:
dz_en_file = "HHep_fci_cc_pVDZ_Energies.npy"
dz_mu_file = "HHep_fci_cc_pVDZ_Dipoles.npy"
tz_en_file = "HHep_fci_cc_pVTZ_Energies.npy"
tz_mu_file = "HHep_fci_cc_pVTZ_Dipoles.npy"
qz_en_file = "HHep_fci_cc-pVQZ_Energies.npy"
qz_mu_file = "HHep_fci_cc-pVQZ_Dipoles.npy"



In [5]:
dz_en = np.load(dz_en_file)
dz_mu = np.load(dz_mu_file)
tz_en = np.load(tz_en_file)
tz_mu = np.load(tz_mu_file)
qz_en = np.load(qz_en_file)
qz_mu = np.load(qz_mu_file)

In [7]:
print(dz_en[2]-dz_en[0])
print(dz_mu[0,2,:])

0.976056825139936
[ 1.25954919e-16 -1.27793281e-17 -7.68441197e-01]


In [8]:
print(tz_en[2]-tz_en[0])
print(tz_mu[0,2,:])

0.9654959008595623
[-1.02338057e-15  1.02925559e-16 -8.04009957e-01]


In [9]:
print(qz_en[2]-qz_en[0])
print(qz_mu[0,2,:])

0.9637811053396552
[-2.43803478e-15  1.93783435e-15  8.07522496e-01]
