In [1]:
import numpy as np
import psi4
psi4.core.set_output_file("c10h8.out")

In [2]:
mol_str = """
0 1
C            0.000004551444    -0.711108766560     0.000010757138
C           -0.000004765464     0.711109074728     0.000001509641
C            1.231111212344    -1.392932324772    -0.000008872321
C            1.231092818353     1.392949010021    -0.000005886632
C           -1.231092617348    -1.392949084219     0.000002684292
C           -1.231111293835     1.392932340511     0.000007560162
C            2.416252154882    -0.702767074233    -0.000017781801
C            2.416242565430     0.702799552187    -0.000000723902
C           -2.416242703804    -0.702799153654     0.000010510747
C           -2.416251802225     0.702766484279     0.000002457080
H            1.229116150588    -2.471858679894    -0.000015215757
H            1.229083140542     2.471874840369    -0.000007074480
H           -1.229084430358    -2.471875468868    -0.000008700875
H           -1.229118355038     2.471858460776     0.000007352885
H            3.350158261997    -1.238508894745    -0.000013806252
H            3.350141246250     1.238554060765     0.000000769827
H           -3.350140729721    -1.238555163085     0.000018452996
H           -3.350156710411     1.238510150658    -0.000008144872
symmetry c1
"""

options_dict = {
    "basis": "cc-pVDZ",
    "scf_type": "pk",
    "e_convergence": 1e-10,
    "d_convergence": 1e-10,
    'num_roots' : 6,
    'frozen_docc' : [28],
    'active' : [12],
    'TDM' :  True,
    'OPDM': True,
    'dipmom' : True
}

mol = psi4.geometry(mol_str)
psi4.set_options(options_dict)
scf_e, wfn = psi4.energy('SCF', return_wfn=True)
fci_energy, wfn = psi4.energy('fci',ref_wfn=wfn, return_wfn=True)

In [3]:
ci_e, wfn = psi4.energy('fci',ref_wfn=wfn, return_wfn=True)
ener = psi4.get_variable('CI ROOT 0 -> ROOT 2 EXCITATION ENERGY')
print(fci_energy)
print(ener)



-383.43284824492974
0.0


/var/folders/hs/493lh3390kv8z7b8n8zv_p580000gp/T/ipykernel_8971/1586369344.py:2: FutureWarning: Using `psi4.core.get_variable` instead of `psi4.core.variable` (or `psi4.core.scalar_variable` for scalar variables only) is deprecated, and in 1.4 it will stop working

  ener = psi4.get_variable('CI ROOT 0 -> ROOT 2 EXCITATION ENERGY')


In [4]:

#transition density matrix
opdm_0 = wfn.get_opdm(1,4,"SUM", True)
dm = opdm_0.to_array()
print(dm)


#two electron integral
mints = psi4.core.MintsHelper(wfn.basisset())
I = mints.ao_eri()
D = I.to_array()
print(I.np)

#get transition dipole moment
props = ['DIPOLE', 'TRANSITION_DIPOLE']
psi4.properties('detci',properties=props)
M = ['X','Y','Z']
for i in range(6):
        for j in M:
                dipole=psi4.get_variable('CI ROOT %d -> ROOT %d DIPOLE %s'%(i,i+1,j))
                print('CI ROOT %d -> ROOT %d DIPOLE %s = %s'%(i,i+1,j,dipole))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[[[ 3.50642730e+00 -1.16833169e+00  4.30158715e-01 ...  7.68354632e-15
     1.36181915e-09 -7.92507636e-10]
   [-1.16833169e+00  1.29614536e+00  4.78712299e-01 ...  5.53077676e-13
     9.80265804e-08 -5.70463511e-08]
   [ 4.30158715e-01  4.78712299e-01  6.31050881e-01 ...  1.17539812e-09
     2.08325635e-04 -1.21234641e-04]
   ...
   [ 7.68354632e-15  5.53077676e-13  1.17539812e-09 ...  1.35646099e-01
     1.10636151e-08 -6.43844630e-09]
   [ 1.36181915e-09  9.80265804e-08  2.08325635e-04 ...  1.10636151e-08
     1.37606996e-01 -1.14113967e-03]
   [-7.92507636e-10 -5.70463511e-08 -1.21234641e-04 ... -6.43844630e-09
    -1.14113967e-03  1.36310182e-01]]

  [[-1.16833169e+00  4.18284095e-01 -1.26918055e-01 ... -1.65733911e-15
    -2.93744066e-10  1.70943708e-10]
   [ 4.18284095e-01 -3.56592370e-01 -9.49306158e-02 ... -1.19298669e-13


CI ROOT 0 -> ROOT 1 DIPOLE X = 0.02797154322226563
CI ROOT 0 -> ROOT 1 DIPOLE Y = -1.1506441905892247e-06
CI ROOT 0 -> ROOT 1 DIPOLE Z = -1.5094161362379692e-06
CI ROOT 1 -> ROOT 2 DIPOLE X = 0.0
CI ROOT 1 -> ROOT 2 DIPOLE Y = 0.0
CI ROOT 1 -> ROOT 2 DIPOLE Z = 0.0
CI ROOT 2 -> ROOT 3 DIPOLE X = 0.0
CI ROOT 2 -> ROOT 3 DIPOLE Y = 0.0
CI ROOT 2 -> ROOT 3 DIPOLE Z = 0.0
CI ROOT 3 -> ROOT 4 DIPOLE X = 0.0
CI ROOT 3 -> ROOT 4 DIPOLE Y = 0.0
CI ROOT 3 -> ROOT 4 DIPOLE Z = 0.0
CI ROOT 4 -> ROOT 5 DIPOLE X = 0.0
CI ROOT 4 -> ROOT 5 DIPOLE Y = 0.0
CI ROOT 4 -> ROOT 5 DIPOLE Z = 0.0
CI ROOT 5 -> ROOT 6 DIPOLE X = 0.0
CI ROOT 5 -> ROOT 6 DIPOLE Y = 0.0
CI ROOT 5 -> ROOT 6 DIPOLE Z = 0.0


/var/folders/hs/493lh3390kv8z7b8n8zv_p580000gp/T/ipykernel_8971/2200516553.py:19: FutureWarning: Using `psi4.core.get_variable` instead of `psi4.core.variable` (or `psi4.core.scalar_variable` for scalar variables only) is deprecated, and in 1.4 it will stop working

  dipole=psi4.get_variable('CI ROOT %d -> ROOT %d DIPOLE %s'%(i,i+1,j))


Should look at 0->2 transition polarized along Y or the 0->5 transition polarized along Y
0->2: omega = 

At the CASCI(10,10)/cc-pVDZ level:
   @CI 16:     0   -383.432630675633   2.3093E-14   1.5364E-06 c
   @CI 16:     1   -383.229174086435   -7.1054E-15   2.1810E-06 c
   @CI 16:     2   -383.214958443052   3.5527E-15   2.5621E-06 c
   @CI 16:     3   -383.160173307314   -1.4211E-14   2.8093E-06 c
   @CI 16:     4   -383.150441547330   -9.3614E-11   3.6503E-06 c
   @CI 16:     5   -383.136370898717   2.8422E-14   2.1271E-06 c


Properties computed using the CI ROOT 0 -> ROOT 1 density matrix


Transition Multipole Moments:

 ------------------------------------------------------------------------------------
     Multipole            Electronic (a.u.)      Nuclear  (a.u.)        Total (a.u.)
 ------------------------------------------------------------------------------------

 L = 1.  Multiply by 2.5417464519 to convert [e a0] to [Debye]
 Dipole X            :         -0.0109742            0.0000000           -0.0109742
 Dipole Y            :          0.0000004            0.0000000            0.0000004
 Dipole Z            :          0.0000006            0.0000000            0.0000006
 Magnitude           :                                                    0.0109742

 ------------------------------------------------------------------------------------

Properties computed using the CI ROOT 0 -> ROOT 2 density matrix


Transition Multipole Moments:

 ------------------------------------------------------------------------------------
     Multipole            Electronic (a.u.)      Nuclear  (a.u.)        Total (a.u.)
 ------------------------------------------------------------------------------------

 L = 1.  Multiply by 2.5417464519 to convert [e a0] to [Debye]
 Dipole X            :          0.0000053            0.0000000            0.0000053
 Dipole Y            :         -0.8601870            0.0000000           -0.8601870
 Dipole Z            :         -0.0000003            0.0000000           -0.0000003
 Magnitude           :                                                    0.8601870

 ------------------------------------------------------------------------------------

Properties computed using the CI ROOT 0 -> ROOT 3 density matrix


Transition Multipole Moments:

 ------------------------------------------------------------------------------------
     Multipole            Electronic (a.u.)      Nuclear  (a.u.)        Total (a.u.)
 ------------------------------------------------------------------------------------

 L = 1.  Multiply by 2.5417464519 to convert [e a0] to [Debye]
 Dipole X            :         -0.0000005            0.0000000           -0.0000005
 Dipole Y            :          0.0000002            0.0000000            0.0000002
 Dipole Z            :          0.0000026            0.0000000            0.0000026
 Magnitude           :                                                    0.0000026

 ------------------------------------------------------------------------------------

Properties computed using the CI ROOT 0 -> ROOT 4 density matrix


Transition Multipole Moments:

 ------------------------------------------------------------------------------------
     Multipole            Electronic (a.u.)      Nuclear  (a.u.)        Total (a.u.)
 ------------------------------------------------------------------------------------

 L = 1.  Multiply by 2.5417464519 to convert [e a0] to [Debye]
 Dipole X            :          0.0000016            0.0000000            0.0000016
 Dipole Y            :          0.0000007            0.0000000            0.0000007
 Dipole Z            :          0.0000006            0.0000000            0.0000006
 Magnitude           :                                                    0.0000018

 ------------------------------------------------------------------------------------

Properties computed using the CI ROOT 0 -> ROOT 5 density matrix


Transition Multipole Moments:

 ------------------------------------------------------------------------------------
     Multipole            Electronic (a.u.)      Nuclear  (a.u.)        Total (a.u.)
 ------------------------------------------------------------------------------------

 L = 1.  Multiply by 2.5417464519 to convert [e a0] to [Debye]
 Dipole X            :         -0.0000277            0.0000000           -0.0000277
 Dipole Y            :          1.3532848            0.0000000            1.3532848
 Dipole Z            :         -0.0000043            0.0000000           -0.0000043
 Magnitude           :                                                    1.3532848

 ------------------------------------------------------------------------------------




In [3]:
E = np.array([-383.432630675633, -383.229174086435, -383.214958443052, -383.160173307314, -383.150441547330, -383.136370898717])
omega_02 = E[2]-E[0]
omega_05 = E[5]-E[0]

print(omega_02)
print(omega_05)

0.21767223258098056
0.29625977691597427
